-- MySQL Script generated by MySQL Workbench
-- 06/10/15 15:39:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema localdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `localdb` ;

-- -----------------------------------------------------
-- Schema localdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `localdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `localdb` ;

-- -----------------------------------------------------
-- Table `localdb`.`template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `localdb`.`template` ;

CREATE TABLE IF NOT EXISTS `localdb`.`template` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localdb`.`element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `localdb`.`element` ;

CREATE TABLE IF NOT EXISTS `localdb`.`element` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localdb`.`template_has_element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `localdb`.`template_has_element` ;

CREATE TABLE IF NOT EXISTS `localdb`.`template_has_element` (
  `id` INT NOT NULL,
  `template_id` INT NOT NULL,
  `element_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_template_has_element_element1_idx` (`element_id` ASC),
  INDEX `fk_template_has_element_template_idx` (`template_id` ASC),
  CONSTRAINT `fk_template_has_element_template`
    FOREIGN KEY (`template_id`)
    REFERENCES `localdb`.`template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_template_has_element_element1`
    FOREIGN KEY (`element_id`)
    REFERENCES `localdb`.`element` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localdb`.`analiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `localdb`.`analiz` ;

CREATE TABLE IF NOT EXISTS `localdb`.`analiz` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `template_id` INT NOT NULL,
  PRIMARY KEY (`id`, `template_id`),
  INDEX `fk_analiz_template1_idx` (`template_id` ASC),
  CONSTRAINT `fk_analiz_template1`
    FOREIGN KEY (`template_id`)
    REFERENCES `localdb`.`template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `localdb`.`analiz_has_element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `localdb`.`analiz_has_element` ;

CREATE TABLE IF NOT EXISTS `localdb`.`analiz_has_element` (
  `id` INT NOT NULL,
  `analiz_id` INT NOT NULL,
  `element_id` INT NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_analiz_has_element_element1_idx` (`element_id` ASC),
  INDEX `fk_analiz_has_element_analiz1_idx` (`analiz_id` ASC),
  CONSTRAINT `fk_analiz_has_element_analiz1`
    FOREIGN KEY (`analiz_id`)
    REFERENCES `localdb`.`analiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_analiz_has_element_element1`
    FOREIGN KEY (`element_id`)
    REFERENCES `localdb`.`element` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
